### ISSUE TITLE
How to get raw video data?

### ISSUE THREAD

**Issue by Zeyu1226-mt** [jackwu502/NSVA#11]
Hello, I am very interested in your work, and I would like to continue my research on your basis. But now I need to use the original video data to do some target detection and other operations. Could you please provide the original video data of each clip below? Thank you very much！！！

**Comment by jackwu502** [comment]
If you would like to download the raw mp4 videos that we use for our dataset, you can use the following code

cd tools
python collect_videos.py

**Comment by Zeyu1226-mt** [comment]
Thank you very much!
