### ISSUE TITLE
Feature extract for my own video

### ISSUE THREAD

**Issue by R00Kie-Liu** [jackwu502/NSVA#4]
Thanks for your great contribution. I do learn much from your paper and code.

Can you release more details about the feature extraction of raw videos? For example, the detailed version of video networks and the pre-processing of videos.  

In this way, we can extend your method into various videos.

Looking forward to your reply!

**Comment by R00Kie-Liu** [comment]
I have found the S3D feature extractor in visual_utils.py. Can you share more about TimeSformer (e.g., the code base you used for Timesformer)?

**Comment by jackwu502** [comment]
Hi, thanks for your question. To extract TimeSformer features, you can first clone the official repo by running git clone https://github.com/facebookresearch/TimeSformer.git. Then cp tools/timesformer_features_extraction.py to the TimeSformer folder. Change the paths in timesformer_features_extraction.py to your local paths then run the script. Let me know if there is any questions from you. Thanks.

**Comment by jackwu502** [comment]
> I have found the S3D feature extractor in visual_utils.py. Can you share more about TimeSformer (e.g., the code base you used for Timesformer)?

Hi, thanks for your question. To extract TimeSformer features, you can first clone the official repo by running git clone https://github.com/facebookresearch/TimeSformer.git. Then cp tools/timesformer_features_extraction.py to the TimeSformer folder. Change the paths in timesformer_features_extraction.py to your local paths then run the script. Let me know if there are any questions. Thanks.

**Comment by R00Kie-Liu** [comment]
Many thanks for your reply. I have obtained the video-level features for my own basketball videos.

However, I note that the complete model requires 
(1) an object detector for players, ball, and basket
(2) A court segmentation model. They are used to extract fine-grained features.

Are they available in your provided code base? Or do I need to devise and train them by myself?

**Comment by jackwu502** [comment]
(1) We utilized Yolov5 (https://github.com/ultralytics/yolov5) for detecting players, the ball, and the basket. To identify players, we employed the pre-trained yolov5m6 model available in the official yolov5 repository. Consequently, this approach enables us to detect all individuals present in a given video. As for ball and basket detection, we trained Yolov5 using our annotated data. You can download the model weights from this link: https://www.dropbox.com/s/4v41u617jnlsspw/best.pt.

(2) To perform court segmentation, we employed the following code: https://github.com/luyangzhu/NBA-Players. The code provided a reliable pre-trained model for court segmentation.

**Comment by jackwu502** [comment]
> Many thanks for your reply. I have obtained the video-level features for my own basketball videos.
> 
> However, I note that the complete model requires (1) an object detector for players, ball, and basket (2) A court segmentation model. They are used to extract fine-grained features.
> 
> Are they available in your provided code base? Or do I need to devise and train them by myself?

(1) We utilized Yolov5 (https://github.com/ultralytics/yolov5) for detecting players, the ball, and the basket. To identify players, we employed the pre-trained yolov5m6 model available in the official yolov5 repository. Consequently, this approach enables us to detect all individuals present in a given video. As for ball and basket detection, we trained Yolov5 using our annotated data. You can download the model weights from this link: https://www.dropbox.com/s/4v41u617jnlsspw/best.pt.

(2) To perform court segmentation, we employed the following code: https://github.com/luyangzhu/NBA-Players. The code provided a reliable pre-trained model for court segmentation.

**Comment by gigasurgeon** [comment]
How do you get the ViT features? Do you use the Vit model present in the timesformer itself for each image or use an official repo for ViT?
