### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/disk/0/scratch/jack/nsva/Univl_bbxfea/UniVL-main/action_list .json'

### ISSUE THREAD

**Issue by striveforx** [jackwu502/NSVA#5]
Hello dear author, I am very interested in your research, but I encountered some problems while running the code. When I was doing Video captioning, this error occurred: FileNotFoundError: [Errno 2] No such file or directory: '/disk/0/scratch/jack/nsva/Univl_bbxfea/UniVL-main/action_list .json', may I ask where to get this file, it seems that there is no one in dataset prepare.

**Comment by JoeHEZHAO** [comment]
Can you change the path to your local directory path of this file `./SportsFormer/action_list.json` ?
