### ISSUE TITLE
How to generate the player names in video captioning?

### ISSUE THREAD

**Issue by Zeyu1226-mt** [jackwu502/NSVA#6]
Very meaningful work. Thank you for your contributions to this area. I have a question for you: How does your transformer-based network generate text descriptions with player names？

**Comment by jackwu502** [comment]
Hi, after you run our code, you should see a hyp.txt generated under your output_dir. The hyp.txt should contain entries like: jump ball player202355 vs . player1628389 : tip to player203482, player201937 p . foul, etc. To replace player token with the real player name, you should construct a mapping using the original data: https://www.dropbox.com/home/NbaGameDataCollectionon/NSVA_Data?preview=0021800013-dal-vs-phx.csv. In the above csv, two columns you may pay attention to are personId and playerNameI. You can write a python code to go through all original csvs and construct a mapping that can help you to replace the player token with the real player name.

**Comment by Zeyu1226-mt** [comment]
> Hi, after you run our code, you should see a hyp.txt generated under your output_dir. The hyp.txt should contain entries like: jump ball player202355 vs . player1628389 : tip to player203482, player201937 p . foul, etc. To replace player token with the real player name, you should construct a mapping using the original data: https://www.dropbox.com/home/NbaGameDataCollectionon/NSVA_Data?preview=0021800013-dal-vs-phx.csv. In the above csv, two columns you may pay attention to are personId and playerNameI. You can write a python code to go through all original csvs and construct a mapping that can help you to replace the player token with the real player name.

Thank you for sharing, I also have some questions for you:
1. The link (https://www.dropbox.com/home/NbaGameDataCollectionon/NSVA_Data?preview=0021800013-dal-vs-phx.csv) shows that the file no longer exists. Could you please upload it again? 
2. I'm still confused about how the visual features generate player names. There is no player identification related to training and operation. And my guess is that, during training, the data contains player names, and the model remembers those names. During the test, according to the parameter memory, the text with the name is output. 
3. Also, why use csv map names? Why don't you just use text with names when training, instead of direct using numbers?

**Comment by jackwu502** [comment]
Hi,
1.  please use this link instead: https://www.dropbox.com/sh/x3zpttp7bjevb3r/AAAeFLnIeBMBXa9DNQD4a8TOa?dl=0. 
2. During training, texts contain anonymized player tokens such as player202355 and player203482, enabling the model to learn to output these tokens after training.
3. In NLP, sentence delexicalization is a common and useful technique for improving a model's generalization ability. More importantly, by replacing real player names with anonymized player tokens, the model is less likely to hallucinate and invent names that are not those of NBA players. For example, "Li Ming" is a human name but not that of an NBA player.

**Comment by Zeyu1226-mt** [comment]
> Hi,
> 
> 1. please use this link instead: https://www.dropbox.com/sh/x3zpttp7bjevb3r/AAAeFLnIeBMBXa9DNQD4a8TOa?dl=0.
> 2. During training, texts contain anonymized player tokens such as player202355 and player203482, enabling the model to learn to output these tokens after training.
> 3. In NLP, sentence delexicalization is a common and useful technique for improving a model's generalization ability. More importantly, by replacing real player names with anonymized player tokens, the model is less likely to hallucinate and invent names that are not those of NBA players. For example, "Li Ming" is a human name but not that of an NBA player.

Thank you for your reply
