### ISSUE TITLE
About the meaning of special symbols

### ISSUE THREAD

**Issue by Zeyu1226-mt** [jackwu502/NSVA#8]
What do <T1>, <T2>, <T3>, and <T4> each represent？Thank you very much.

**Comment by jackwu502** [comment]
Sorry, I do not understand your question, could you elaborate on this?

**Comment by Xiyu-AI** [comment]
> Sorry, I do not understand your question, could you elaborate on this?

What do <T1>, <T2>, <T3>, and <T4> each represent

**Comment by Zeyu1226-mt** [comment]
Sorry, this system does not show the special symbols. For example, in ourds_description_only.json, there are many  special symbols in "caption", like  {"caption": "T1_PLAYER201599 PLAYER1628386 PLAYER1626156".....  What do "T1", "T2", "T3" and "T4" mean?

**Comment by jackwu502** [comment]
Hi, the T1, T2, T3, and T4 represent different tasks. You can ignore T4, as, to the best of my recollection, we have never used it. T1 denotes the player recognition task, T2 the action recognition task, and T3 the video captioning task. When you execute code for a specific task, only the entries with the corresponding task header will be utilized. For instance, if you wish to run the code for the video captioning task, only entries starting with < T3 >_ will be used.

**Comment by Zeyu1226-mt** [comment]
Thank you for your reply.
