### ISSUE TITLE
--features_path data/ourds_videos_features.pickle

### ISSUE THREAD

**Issue by Zeyu1226-mt** [jackwu502/NSVA#9]
Hello, in main_task_caption.py code (--features_path data/ourds_videos_features.pickle), where to download the ourds_videos_features.pickle? Should I use ourds_videos_timesformer_features.pickle instead??

Thank you very much!

**Comment by jackwu502** [comment]
Hi. Yes, please use ourds_videos_timesformer_features.pickle instead.
